modLoader="javafml"
loaderVersion="[43,)"
license="MIT"
issueTrackerURL="https://github.com/legoblocks/renderer/issues"

[[mods]]
modId="legoblocks"
version="${file.jarVersion}"
displayName="LEGO Blocks Renderer"
description='''Custom rendering system for LEGO-style blocks in Minecraft with proper non-cube shapes and aesthetics.'''
credits="LegoBlocks Team"
authors="LegoBlocks Team"
displayURL="https://github.com/legoblocks/renderer"

[[dependencies.legoblocks]]
modId="forge"
mandatory=true
versionRange="[43,)"
ordering="NONE"
side="BOTH"

[[dependencies.legoblocks]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2,1.20)"
ordering="NONE"
side="BOTH"
