name: Issue to Pull Request
on:
  issues:
    types: [labeled]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  generate-pr-from-issue:
    if: github.event.label.name == 'ready-to-implement'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install Cursor CLI
      run: |
        curl https://cursor.com/install -fsS | bash
        echo "$HOME/.cursor/bin" >> $GITHUB_PATH

    - name: Configure git identity
      run: |
        git config --global user.name "cursor-bot"
        git config --global user.email "cursor-bot@users.noreply.github.com"

    - name: Generate PR from Issue
      env:
        CURSOR_API_KEY: ${{ secrets.CURSOR_API_KEY }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Create implementation branch
        branch_name="implement-issue-${{ github.event.issue.number }}-$(date +%s)"
        git checkout -b "$branch_name"
        
        # Parse repository owner and name
        REPO_OWNER=$(echo "${{ github.repository }}" | cut -d'/' -f1)
        REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2)
        
        # Run cursor agent to implement the issue requirements
        cursor-agent --model sonnet-4 -f --output-format text -p "Read GitHub issue ${{ github.event.issue.number }} details using gh issue view command. Analyze the requirements and create/modify files as needed to implement the feature. After completing implementation, output 'IMPLEMENTATION_COMPLETE: Ready for PR creation'. Use shell commands freely to read files, understand codebase, and create implementation files." 2>&1 | tee cursor_implementation.log
        
        # Push branch and create PR using GitHub CLI
        if grep -q "IMPLEMENTATION_COMPLETE:" cursor_implementation.log; then
          # Push the branch
          git add .
          git commit -m "Implement issue #${{ github.event.issue.number }}
          
          Auto-generated implementation from TRD requirements.
          
          Closes #${{ github.event.issue.number }}"
          git push -u origin "$branch_name"
          
          # Create PR using GitHub CLI
          PR_URL=$(gh pr create --title "Implement issue #${{ github.event.issue.number }}" \
            --body "Auto-generated implementation for issue #${{ github.event.issue.number }}.

          This PR implements the requirements specified in the TRD-generated issue.
          
          Closes #${{ github.event.issue.number }}" \
            --label "trd-generated,implementation" \
            --base main \
            --head "$branch_name" \
            --json url --jq .url)
          
          gh issue comment ${{ github.event.issue.number }} --body "✅ Implementation PR created: $PR_URL"
        else
          gh issue comment ${{ github.event.issue.number }} --body "❌ Implementation failed - Check workflow logs"
          exit 1
        fi
