name: Issue to Pull Request
on:
  issues:
    types: [labeled]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  generate-pr-from-issue:
    if: github.event.label.name == 'ready-to-implement' && contains(github.event.issue.labels.*.name, 'trd-generated')
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install Cursor CLI
      run: |
        curl https://cursor.com/install -fsS | bash
        echo "$HOME/.cursor/bin" >> $GITHUB_PATH

    - name: Configure git identity
      run: |
        git config --global user.name "cursor-bot"
        git config --global user.email "cursor-bot@users.noreply.github.com"

    - name: Setup MCP Configuration
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        mkdir -p ~/.cursor
        cat > ~/.cursor/mcp.json << 'EOF'
        {
          "mcpServers": {
            "github": {
              "url": "https://api.githubcopilot.com/mcp/",
              "headers": {
                "Authorization": "Bearer $GITHUB_TOKEN"
              }
            }
          }
        }
        EOF
        
        # Replace placeholder with actual token
        sed -i "s/\$GITHUB_TOKEN/$GITHUB_TOKEN/g" ~/.cursor/mcp.json

    - name: Generate PR from Issue
      env:
        CURSOR_API_KEY: ${{ secrets.CURSOR_API_KEY }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Create implementation branch
        branch_name="implement-issue-${{ github.event.issue.number }}-$(date +%s)"
        git checkout -b "$branch_name"
        
        # Parse repository owner and name
        REPO_OWNER=$(echo "${{ github.repository }}" | cut -d'/' -f1)
        REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2)
        
        # Run cursor agent to implement the issue requirements
        cursor-agent -p "
        I need you to implement the requirements from GitHub issue and create a pull request.
        
        Repository Owner: $REPO_OWNER  
        Repository Name: $REPO_NAME
        Issue Number: ${{ github.event.issue.number }}
        
        Steps:
        1. Read the issue details using GitHub CLI: gh issue view ${{ github.event.issue.number }}
        2. Analyze the issue requirements and find related TRD files in the repository
        3. Generate the necessary code files and changes (create/modify files as needed)
        4. After creating all necessary files, output: 'IMPLEMENTATION_COMPLETE: Ready for PR creation'
        
        Make sure to create actual code files in the repository that implement the requirements.
        " 2>&1 | tee cursor_implementation.log
        
        # Push branch and create PR using GitHub CLI
        if grep -q "IMPLEMENTATION_COMPLETE:" cursor_implementation.log; then
          # Push the branch
          git add .
          git commit -m "Implement issue #${{ github.event.issue.number }}
          
          Auto-generated implementation from TRD requirements.
          
          Closes #${{ github.event.issue.number }}"
          git push -u origin "$branch_name"
          
          # Create PR using GitHub CLI
          PR_URL=$(gh pr create --title "Implement issue #${{ github.event.issue.number }}" \
            --body "Auto-generated implementation for issue #${{ github.event.issue.number }}.

          This PR implements the requirements specified in the TRD-generated issue.
          
          Closes #${{ github.event.issue.number }}" \
            --label "trd-generated,implementation" \
            --base main \
            --head "$branch_name" \
            --json url --jq .url)
          
          gh issue comment ${{ github.event.issue.number }} --body "✅ Implementation PR created: $PR_URL"
        else
          gh issue comment ${{ github.event.issue.number }} --body "❌ Implementation failed - Check workflow logs"
          exit 1
        fi