name: Issue to Pull Request
on:
  issues:
    types: [labeled]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  generate-pr-from-issue:
    if: github.event.label.name == 'ready-to-implement'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install Cursor CLI
      run: |
        curl https://cursor.com/install -fsS | bash
        echo "$HOME/.cursor/bin" >> $GITHUB_PATH

    - name: Configure git identity
      run: |
        git config --global user.name "cursor-bot"
        git config --global user.email "cursor-bot@users.noreply.github.com"

    - name: Generate PR from Issue
      env:
        CURSOR_API_KEY: ${{ secrets.CURSOR_API_KEY }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Create implementation branch
        branch_name="implement-issue-${{ github.event.issue.number }}-$(date +%s)"
        git checkout -b "$branch_name"
        
        # Parse repository owner and name
        REPO_OWNER=$(echo "${{ github.repository }}" | cut -d'/' -f1)
        REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2)
        
        # Create initial commit and PR early for transparency
        echo "# Implementation in progress for issue #${{ github.event.issue.number }}" > IMPLEMENTATION.md
        git add IMPLEMENTATION.md
        git commit -m "Start implementation for issue #${{ github.event.issue.number }}"
        git push -u origin "$branch_name"
        
        # Create draft PR immediately
        gh pr create --title "🚧 WIP: Implement issue #${{ github.event.issue.number }}" \
          --body "🚧 **Work in Progress** - Auto-generated implementation for issue #${{ github.event.issue.number }}.

        This PR implements the requirements specified in the TRD-generated issue.
        
        Progress will be updated with frequent commits.
        
        Closes #${{ github.event.issue.number }}" \
          --base main \
          --head "$branch_name" \
          --draft
          
        # Get PR URL
        PR_URL="https://github.com/${{ github.repository }}/pull/$(gh pr list --head $branch_name --json number --jq '.[0].number')"
        
        gh issue comment ${{ github.event.issue.number }} --body "🚧 Implementation started: $PR_URL"
        
        # Run cursor agent to implement the issue requirements
        cursor-agent --model sonnet-4 -f --output-format text -p "Read GitHub issue ${{ github.event.issue.number }} details using gh issue view command. Analyze the requirements and create/modify files as needed to implement the feature. IMPORTANT: Make frequent commits with descriptive messages using 'git add . && git commit -m \"descriptive message\" && git push origin $branch_name' after each significant change. Provide progress updates by commenting on the issue with: gh issue comment ${{ github.event.issue.number }} --body 'Progress update: [what you are working on]'. After completing implementation, output 'IMPLEMENTATION_COMPLETE: Ready for PR creation'. Use shell commands freely to read files, understand codebase, and create implementation files." 2>&1 | tee cursor_implementation.log
        
        # Mark PR as ready for review
        if grep -q "IMPLEMENTATION_COMPLETE:" cursor_implementation.log; then
          # Final commit
          git add .
          git commit -m "Complete implementation for issue #${{ github.event.issue.number }}" || echo "No final changes to commit"
          git push origin "$branch_name"
          
          # Mark PR as ready for review
          gh pr ready "$PR_URL"
          gh pr edit "$PR_URL" --title "Implement issue #${{ github.event.issue.number }}"
          
          gh issue comment ${{ github.event.issue.number }} --body "✅ Implementation complete and ready for review: $PR_URL"
        else
          gh issue comment ${{ github.event.issue.number }} --body "❌ Implementation failed - Check workflow logs and PR: $PR_URL"
          exit 1
        fi
