name: TRD to GitHub Issues
on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  create-issues-from-trd:
    if: github.event.issue.pull_request != null && (contains(github.event.comment.body, '@cursor') || contains(github.event.comment.body, '/create-issues'))
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout PR
      uses: actions/checkout@v4
      
    - name: Install Cursor CLI
      run: |
        curl https://cursor.com/install -fsS | bash
        echo "$HOME/.cursor/bin" >> $GITHUB_PATH

    - name: Configure git identity
      run: |
        git config --global user.name "cursor-bot"
        git config --global user.email "cursor-bot@users.noreply.github.com"

    - name: Setup MCP Configuration
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        mkdir -p ~/.cursor
        cat > ~/.cursor/mcp.json << 'EOF'
        {
          "mcpServers": {
            "github": {
              "url": "https://api.githubcopilot.com/mcp/",
              "headers": {
                "Authorization": "Bearer $GITHUB_TOKEN"
              }
            }
          }
        }
        EOF
        
        # Replace placeholder with actual token
        sed -i "s/\$GITHUB_TOKEN/$GITHUB_TOKEN/g" ~/.cursor/mcp.json

    - name: Generate Issues from TRD
      env:
        CURSOR_API_KEY: ${{ secrets.CURSOR_API_KEY }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Get TRD files from PR and read their contents directly from filesystem
        TRD_FILES=$(gh pr diff ${{ github.event.issue.number }} --name-only | grep -E '\.(md|txt)$')
        echo "Found TRD files: $TRD_FILES"
        
        if [[ -z "$TRD_FILES" ]]; then
          echo "❌ No TRD files found in PR"
          gh pr comment ${{ github.event.issue.number }} --body "❌ No TRD files (.md or .txt) found in this PR"
          exit 1
        fi
        
        # Read TRD file contents directly from the repository
        TRD_CONTENT=""
        for file in $TRD_FILES; do
          if [[ -f "$file" ]]; then
            echo "Reading $file..."
            TRD_CONTENT="$TRD_CONTENT\n\n=== $file ===\n$(cat "$file")"
          fi
        done
        
        # Parse repository owner and name
        REPO_OWNER=$(echo "${{ github.repository }}" | cut -d'/' -f1)
        REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2)
        
        # Run cursor agent with GitHub MCP server
        cursor-agent -p "
        STOP! You are NOT allowed to create files, write code, or generate templates. 
        
        You MUST use the GitHub MCP server to create LIVE GitHub issues in this repository: $REPO_OWNER/$REPO_NAME
        
        TRD to analyze: $TRD_CONTENT
        
        MANDATORY ACTIONS:
        1. Use GitHub MCP server create_issue function calls ONLY
        2. Each call creates ONE real GitHub issue in the live repository
        3. Function parameters: owner='$REPO_OWNER', repo='$REPO_NAME', title='Issue Title', body='Issue Description', labels=['trd-generated', 'planning']
        4. After each successful create_issue call, output: 'CREATED_ISSUE_URL: https://github.com/$REPO_OWNER/$REPO_NAME/issues/NUMBER'
        
        EXAMPLE MCP CALL:
        create_issue(owner='$REPO_OWNER', repo='$REPO_NAME', title='[PLANNING] LEGO Block System', body='Planning phase for LEGO block system implementation...', labels=['trd-generated', 'planning'])
        
        FORBIDDEN:
        - Do NOT write files
        - Do NOT create templates  
        - Do NOT generate code
        - Do NOT use Write, Edit, or any file tools
        
        REQUIRED:
        - Call GitHub MCP create_issue function for each issue
        - Use exact function name: create_issue
        - Include owner, repo, title, body, and labels parameters
        - Generate real issues that appear in GitHub UI
        " 2>&1 | tee cursor_output.log
        
        # Extract issue URLs from cursor output and comment on PR
        if grep -q "CREATED_ISSUE_URL:" cursor_output.log; then
          CREATED_ISSUES=$(grep "CREATED_ISSUE_URL:" cursor_output.log | sed 's/.*CREATED_ISSUE_URL: //' | tr '\n' ' ')
          gh pr comment ${{ github.event.issue.number }} --body "✅ TRD analysis complete - Created issues: $CREATED_ISSUES"
        else
          gh pr comment ${{ github.event.issue.number }} --body "❌ TRD analysis failed - Check workflow logs for details"
          exit 1
        fi
