name: TRD to GitHub Issues
on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  create-issues-from-trd:
    if: github.event.issue.pull_request != null && contains(github.event.comment.body, '/create-issues')
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout PR
      uses: actions/checkout@v4
      
    - name: Install Cursor CLI
      run: |
        curl https://cursor.com/install -fsS | bash
        echo "$HOME/.cursor/bin" >> $GITHUB_PATH


    - name: Create GitHub Issues with Cursor Agent
      env:
        CURSOR_API_KEY: ${{ secrets.CURSOR_API_KEY }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Parse repository owner and name
        REPO_OWNER=$(echo "${{ github.repository }}" | cut -d'/' -f1)
        REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2)
        
        # Run cursor agent to analyze PR TRD files and create GitHub issues
        cursor-agent \
          --model claude-sonnet-4-20250514 \
          --prompt "
        TASK: Find and analyze TRD documents in this PR and create GitHub issues for repository: $REPO_OWNER/$REPO_NAME

        PROCESS:
        1. Use Bash tool to find TRD files (.md or .txt files) in the current directory
        2. Read each TRD file to understand the technical requirements
        3. For each major feature/requirement, create a GitHub issue using this bash command:
           gh issue create --title '[PLANNING] Feature Name' --body 'Description from TRD requirements' --label 'trd-generated,planning' --repo '$REPO_OWNER/$REPO_NAME'
        4. After each successful issue creation, output: 'CREATED_ISSUE_URL: [returned_url]'

        CONSTRAINTS:
        - Use ONLY Bash tool for file operations and gh commands
        - Find TRD files in current directory (*.md, *.txt)
        - Create meaningful issue titles and descriptions based on TRD content
        - No file writing or template creation
        - Execute gh issue create commands directly

        START: Find TRD files and create issues now.
        " 2>&1 | tee cursor_output.log

    - name: Report Results
      if: always()
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Extract issue URLs from cursor output and comment on PR
        if grep -q "CREATED_ISSUE_URL:" cursor_output.log; then
          CREATED_ISSUES=$(grep "CREATED_ISSUE_URL:" cursor_output.log | sed 's/.*CREATED_ISSUE_URL: //' | tr '\n' ' ')
          gh pr comment ${{ github.event.issue.number }} --body "✅ TRD analysis complete - Created issues: $CREATED_ISSUES"
        else
          gh pr comment ${{ github.event.issue.number }} --body "❌ TRD analysis failed - Check workflow logs for details"
          exit 1
        fi
